- hosts: all
  remote_user: root

  tasks:
    - name: echo username
      command: cat /etc/shadow
      become: yes
      register: result

    - name: debug result ver
      debug: var=result

      #     - name: Install OpenLDAP
      #       yum:
      #           name: openldap-servers, openldap-clients
      #           state: latest
      #     - name: Start slapd
      #       service:
      #           name: slapd
      #           state: started



