- hosts: all
  remote_user: root

  tasks:
    - name: get os version
      command: cat /etc/redhat-release
      # become: yes
      register: result
    - name: debug result ver
      debug: var=result

    - name: get karnel information
      command: uname -a
      register: result
    - name: debug result ver
      debug: var=result

    - name: Install OpenLDAP servers and clients
      yum:
          name: "{{ packages }}"
          state: latest
      vars:
          packages:
              - openldap-servers
              - openldap-clients
      become: yes
      register: result
    - name: display package install
      debug: var=result

    - name: start slapd (OpenLDAP)
      systemd:
          name: slapd
          state: started
      become: yes
      register: result
    - name: display slapd start result
      debug: var=result




